### ISSUE TITLE
Package fontspec error The font "Comic Sans MS" cannot be found.

### ISSUE THREAD

**Issue by nuke-web3** [w3f/CardsAgainstBlockchain#3]
From zero Latex installed Pop!_OS 22.04 LTS:

```sh
sudo apt install texlive-xetex
make PDFs

! Package fontspec Error: The font "Comic Sans MS" cannot be found.

l.12 \setsansfont
                 {Helvetica}
```
Noob here -what do I need to get the font? The REEADME would be good to mention dependencies :pray: 

https://starlinq.livejournal.com/3396.html
this also failed to change the error :(

**Comment by nuke-web3** [comment]
any chance the _single card_ that needs this font could use another one? :sweat_smile: 
would resolve this for everyone

**Comment by burdges** [comment]
It likely works under maxports' texlive, but yeah I've the same bug under 

One card?  We inherited this fro m cards against cryptography, so it's not a specific card thing.  It's really the back of the card I guess.

**Comment by TriplEight** [comment]
fixed in https://github.com/CardsAgainstBlockchain/CardsAgainstBlockchain/pull/5
